pipeline {
   agent {
     node {
        label 'jenkins-agent-1'
        }
}
    stages {
stage('init'){

        steps {
          script {
           sh """
           cd 01-vpc
           terraform init -reconfigure
           """
          }
      }
}
stage('terraform plan'){

        steps {
          script {
           sh """
           cd 01-vpc
           terraform plan
           """
          }
      }
}
stage('terraform approve'){
  input(
    message: 'select approve or deny for changes?',
    ok: 'Yes', 
    parameters: [
      booleanParam(defaultValue: true, description: 'select approve to apply changes.',name: 'Yes?')
    ]
  )

        steps {
          script {
           sh """
           cd 01-vpc
           terraform apply -auto-approve
           """
          }
      }
}
}
}