pipeline {
   agent {
     node {
        label 'jenkins-agent-1'
        }
}
options {
                timeout(time: 1, unit: 'HOURS') 
            }
parameters {
  action actions: ['deploy_infra', 'destroy_infra'], name: 'terraform'
}
    stages {
stage('init'){

        steps {
          script {
           sh """
           cd 01-vpc
           terraform init -reconfigure
           """
          }
      }
}
stage('terraform plan'){

        steps {
          script {
           sh """
           cd 01-vpc
           terraform plan
           """
          }
      }
}
stage('terraform approve'){
  when {
    action.param == "deploy_infra"
  }
 input {
                message "approve to continue terraform plan infra"
                ok "apply"
                submitter "alice,bob"
                parameters {
                    string(name: 'TERRAFORM', defaultValue: 'apply or deny', description: 'approve to continue terraform plan infra?')
                }
 }

        steps {
          script {
           sh """
           cd 01-vpc
           terraform apply -auto-approve
           """
          }
      }
    }

}
}