pipeline {
   agent  any
  //   node {
  //       label 'jenkins-agent-1'
  //       }

    stages {
      stage('vpc_deploy'){

        steps {
           sh """
           terraform init
           cd 01-vpc
           terraform apply -auto-approve
           
           """
          }
      }
}

}
